name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ruffian
        uses: chartboost/ruff-action@v1
        with:
          path: "./datascience_utilities/"

      - name: Black Source
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./datascience_utilities/"
          version: "22.12.0"
